#!/bin/sh

set -eou pipefail

EXTRACT_DIR=$( mktemp -d );

trap 'test -n "${EXTRACT_DIR}" && rm -rf "${EXTRACT_DIR}' 1 3 15

NAME="${EXTRACT_DIR}/disk.dmg"
DEST="${HOME}/${1}"
LINK="${2}"
cat - > "${NAME}"
mkdir -p "${DEST}" &> /dev/null

hdiutil attach "${NAME}" \
  | awk '/GUID/ { disk=$1 } NF==3 { mount=$3 } END { print disk" "mount }' \
  | while read disk mount; do
  cd "${EXTRACT_DIR}";
  xar -xf ${mount}/*.pkg;
  hdiutil detach $disk >/dev/null;
  cat *.pkg/Payload | gunzip -dc | ( cd "${DEST}"; cpio -imd ) >& /dev/null;
done

if test -n "${LINK:-}"; then
  cat << EOF
#!/bin/sh

exec "${DEST}/${LINK}" "\${@}"
EOF
fi

rm -rf ${EXTRACT_DIR}
